// ============================================================
// Dữ liệu & i18n Trang quản trị — TP. Quảng Ngãi (mô phỏng)
// Nạp sau js/i18n.js, js/data.js, js/officer-data.js
// ============================================================

Object.assign(window.I18N.vi, {
  ad_portal: 'Quản trị hệ thống',
  ad_users: 'Người dùng',
  ad_officers: 'Cán bộ',
  ad_catalogs: 'Danh mục',
  ad_notifications: 'Thông báo',
  ad_audit: 'Nhật ký hệ thống',
  ad_search_ph: 'Tìm người dùng, danh mục, nhật ký…',

  // Đăng nhập quản trị
  ad_login_title: 'Đăng nhập Trang quản trị',
  ad_login_sub: 'Khu vực dành riêng cho quản trị viên hệ thống.',
  ad_login_email: 'Email',
  ad_login_email_ph: 'admin@quangngai.gov.vn',
  ad_login_password: 'Mật khẩu',
  ad_login_password_ph: 'Nhập mật khẩu',
  ad_login_submit: 'Đăng nhập',
  ad_login_signing: 'Đang đăng nhập…',
  ad_login_checking: 'Đang kiểm tra phiên đăng nhập…',
  ad_login_err_credentials: 'Email hoặc mật khẩu không đúng.',
  ad_login_err_forbidden: 'Tài khoản này không có quyền truy cập Trang quản trị.',
  ad_login_err_generic: 'Không thể đăng nhập. Vui lòng thử lại.',
  ad_login_required: 'Vui lòng nhập email và mật khẩu.',
  ad_login_back_citizen: 'Về Cổng công dân',

  // Người dùng
  u_create: 'Tạo người dùng',
  u_edit: 'Sửa',
  u_disable: 'Vô hiệu hóa',
  u_enable: 'Kích hoạt',
  u_assign_role: 'Gán vai trò',
  u_role: 'Vai trò',
  u_status: 'Trạng thái',
  u_active: 'Hoạt động',
  u_disabled: 'Vô hiệu',
  u_last_login: 'Đăng nhập gần nhất',
  u_never: 'Chưa từng',
  role_citizen: 'Công dân',
  role_officer: 'Cán bộ',
  role_admin: 'Quản trị viên',
  role_super: 'QT cấp cao',

  // Cán bộ
  o_department: 'Phòng ban',
  o_area: 'Địa bàn',
  o_position: 'Chức vụ',
  o_workload: 'Đang xử lý',
  o_assign_dept: 'Phân công đơn vị',

  // Danh mục
  c_service_categories: 'Lĩnh vực dịch vụ',
  c_services: 'Dịch vụ công',
  c_points: 'Điểm dịch vụ',
  ad_points: 'Điểm dịch vụ',
  sp_add_point: 'Thêm điểm dịch vụ',
  sp_edit_point: 'Sửa điểm dịch vụ',
  sp_click_map: 'Bấm trên bản đồ để đặt vị trí',
  sp_services_offered: 'Dịch vụ tiếp nhận',
  c_feedback_cats: 'Loại phản ánh',
  c_admin_units: 'Đơn vị hành chính',
  c_add: 'Thêm mới',
  c_name_vi: 'Tên (Tiếng Việt)',
  c_name_en: 'Tên (Tiếng Anh)',
  c_icon: 'Biểu tượng',
  c_procedures: 'Số thủ tục',
  c_delete: 'Xóa',
  c_delete_confirm: 'Bạn chắc chắn muốn xóa mục này?',
  c_province: 'Tỉnh/TP',
  c_district: 'Quận/Huyện/TX',
  c_ward: 'Phường/Xã',
  c_code: 'Mã',
  c_level: 'Cấp',
  c_displayorder: 'Thứ tự hiển thị',
  c_status: 'Trạng thái',
  c_active: 'Hoạt động',
  c_inactive: 'Vô hiệu',
  c_add_province: 'Thêm tỉnh/TP',
  c_add_ward: 'Thêm phường/xã',
  dt_save_error: 'Lưu thất bại, vui lòng thử lại',
  dt_deleted: 'Đã xóa',
  sp_type: 'Loại điểm',
  sp_type_ubnd: 'UBND / Một cửa',
  sp_type_police: 'Công an',
  sp_type_hospital: 'Y tế',
  sp_type_school: 'Giáo dục',
  sp_type_admincenter: 'Trung tâm HCC',

  // Thông báo
  n_compose: 'Soạn thông báo',
  n_type: 'Loại thông báo',
  n_push: 'Push cá nhân',
  n_broadcast: 'Broadcast toàn dân',
  n_emergency: 'Cảnh báo khẩn cấp',
  n_audience: 'Đối tượng nhận',
  n_all_citizens: 'Toàn bộ công dân',
  n_by_ward: 'Theo phường/xã',
  n_officers_only: 'Chỉ cán bộ',
  n_title: 'Tiêu đề',
  n_content: 'Nội dung',
  n_send_now: 'Gửi ngay',
  n_history: 'Lịch sử gửi',
  n_sent_to: 'người nhận',
  n_recipients: 'Người nhận',
  n_recipients_ph: 'Tìm theo tên hoặc số điện thoại…',
  n_sent: 'Đã gửi thông báo',
  n_emergency_note: 'Cảnh báo khẩn cấp sẽ ghi đè chế độ im lặng và gửi SMS dự phòng.',

  // Audit
  au_time: 'Thời gian',
  au_user: 'Người thực hiện',
  au_action: 'Hành động',
  au_entity: 'Đối tượng',
  au_detail: 'Chi tiết',
  au_ip: 'Địa chỉ IP',
  au_export: 'Xuất Excel',
  au_exported: 'Đã xuất tệp audit-log.csv',
  au_from: 'Từ ngày',
  au_to: 'Đến ngày',
  act_create: 'Tạo mới',
  act_update: 'Cập nhật',
  act_delete: 'Xóa',
  act_login: 'Đăng nhập',
  act_role: 'Gán vai trò',
  act_status: 'Đổi trạng thái',
});

Object.assign(window.I18N.en, {
  ad_portal: 'System Administration',
  ad_users: 'Users',
  ad_officers: 'Officers',
  ad_catalogs: 'Catalogs',
  ad_notifications: 'Notifications',
  ad_audit: 'Audit Log',
  ad_search_ph: 'Search users, catalogs, logs…',

  // Admin sign-in
  ad_login_title: 'Administration sign-in',
  ad_login_sub: 'Restricted area for system administrators.',
  ad_login_email: 'Email',
  ad_login_email_ph: 'admin@quangngai.gov.vn',
  ad_login_password: 'Password',
  ad_login_password_ph: 'Enter password',
  ad_login_submit: 'Sign in',
  ad_login_signing: 'Signing in…',
  ad_login_checking: 'Checking your session…',
  ad_login_err_credentials: 'Incorrect email or password.',
  ad_login_err_forbidden: 'This account does not have administration access.',
  ad_login_err_generic: 'Unable to sign in. Please try again.',
  ad_login_required: 'Please enter your email and password.',
  ad_login_back_citizen: 'Back to Citizen Portal',

  u_create: 'Create user',
  u_edit: 'Edit',
  u_disable: 'Disable',
  u_enable: 'Enable',
  u_assign_role: 'Assign role',
  u_role: 'Role',
  u_status: 'Status',
  u_active: 'Active',
  u_disabled: 'Disabled',
  u_last_login: 'Last login',
  u_never: 'Never',
  role_citizen: 'Citizen',
  role_officer: 'Officer',
  role_admin: 'Administrator',
  role_super: 'Super Admin',

  o_department: 'Department',
  o_area: 'Area',
  o_position: 'Position',
  o_workload: 'In progress',
  o_assign_dept: 'Assign unit',

  c_service_categories: 'Service categories',
  c_services: 'Public services',
  c_points: 'Service points',
  ad_points: 'Service points',
  sp_add_point: 'Add service point',
  sp_edit_point: 'Edit service point',
  sp_click_map: 'Click the map to set location',
  sp_services_offered: 'Available services',
  c_feedback_cats: 'Feedback categories',
  c_admin_units: 'Administrative units',
  c_add: 'Add new',
  c_name_vi: 'Name (Vietnamese)',
  c_name_en: 'Name (English)',
  c_icon: 'Icon',
  c_procedures: 'Procedures',
  c_delete: 'Delete',
  c_delete_confirm: 'Are you sure you want to delete this item?',
  c_province: 'Province',
  c_district: 'District',
  c_ward: 'Ward',
  c_code: 'Code',
  c_level: 'Level',
  c_displayorder: 'Display order',
  c_status: 'Status',
  c_active: 'Active',
  c_inactive: 'Inactive',
  c_add_province: 'Add province',
  c_add_ward: 'Add ward',
  dt_save_error: 'Save failed, please try again',
  dt_deleted: 'Deleted',
  sp_type: 'Point type',
  sp_type_ubnd: 'People’s Committee / One-stop',
  sp_type_police: 'Police',
  sp_type_hospital: 'Health',
  sp_type_school: 'Education',
  sp_type_admincenter: 'Admin Center',

  n_compose: 'Compose notification',
  n_type: 'Notification type',
  n_push: 'Personal push',
  n_broadcast: 'Broadcast to all',
  n_emergency: 'Emergency alert',
  n_audience: 'Audience',
  n_all_citizens: 'All citizens',
  n_by_ward: 'By ward',
  n_officers_only: 'Officers only',
  n_title: 'Title',
  n_content: 'Content',
  n_send_now: 'Send now',
  n_history: 'Send history',
  n_sent_to: 'recipients',
  n_recipients: 'Recipients',
  n_recipients_ph: 'Search by name or phone number…',
  n_sent: 'Notification sent',
  n_emergency_note: 'Emergency alerts override silent mode and send backup SMS.',

  au_time: 'Time',
  au_user: 'User',
  au_action: 'Action',
  au_entity: 'Entity',
  au_detail: 'Detail',
  au_ip: 'IP address',
  au_export: 'Export Excel',
  au_exported: 'Exported audit-log.csv',
  au_from: 'From date',
  au_to: 'To date',
  act_create: 'Create',
  act_update: 'Update',
  act_delete: 'Delete',
  act_login: 'Login',
  act_role: 'Assign role',
  act_status: 'Change status',
});

window.ADATA = {
  me: { name: 'Phạm Quốc Trung', role: { vi: 'Quản trị viên hệ thống', en: 'System Administrator' }, initials: 'QT' },

  roles: ['citizen', 'officer', 'admin', 'super'],
  roleMeta: {
    citizen: { labelKey: 'role_citizen', tone: 'neutral' },
    officer: { labelKey: 'role_officer', tone: 'info' },
    admin:   { labelKey: 'role_admin',   tone: 'warning' },
    super:   { labelKey: 'role_super',   tone: 'danger' },
  },

  users: [
    { id: 'u01', name: 'Nguyễn Thị Minh Hà', phone: '0905 234 671', email: 'minhha.nguyen@gmail.com', role: 'citizen', active: true,  lastLogin: '11/06/2026 08:12' },
    { id: 'u02', name: 'Trần Văn Khoa',      phone: '0913 882 045', email: 'khoa.tran@gmail.com',     role: 'citizen', active: true,  lastLogin: '10/06/2026 16:40' },
    { id: 'u03', name: 'Lê Thị Thu Trang',   phone: '0935 400 218', email: 'trang.le@quangngai.gov.vn', role: 'officer', active: true, lastLogin: '11/06/2026 07:05' },
    { id: 'u04', name: 'Trần Quốc Bảo',      phone: '0918 223 901', email: 'bao.tran@quangngai.gov.vn', role: 'officer', active: true, lastLogin: '11/06/2026 07:31' },
    { id: 'u05', name: 'Phạm Văn Hùng',      phone: '0905 718 442', email: 'hung.pham@quangngai.gov.vn', role: 'officer', active: true, lastLogin: '10/06/2026 14:22' },
    { id: 'u06', name: 'Võ Minh Châu',       phone: '0987 530 119', email: 'chau.vo@quangngai.gov.vn', role: 'officer', active: true, lastLogin: '09/06/2026 09:48' },
    { id: 'u07', name: 'Phạm Quốc Trung',    phone: '0909 112 357', email: 'trung.pham@quangngai.gov.vn', role: 'admin', active: true, lastLogin: '11/06/2026 06:55' },
    { id: 'u08', name: 'Hồ Thị Kim Oanh',    phone: '0935 902 117', email: 'kimoanh.ho@gmail.com',    role: 'citizen', active: false, lastLogin: '22/04/2026 11:30' },
    { id: 'u09', name: 'Đặng Hữu Phước',     phone: '0912 664 873', email: 'phuoc.dang@quangngai.gov.vn', role: 'officer', active: true, lastLogin: '11/06/2026 08:02' },
    { id: 'u10', name: 'Lương Thành Đạt',    phone: '0938 271 506', email: 'dat.luong@quangngai.gov.vn', role: 'super', active: true, lastLogin: '10/06/2026 21:17' },
  ],

  officerProfiles: [
    { id: 'of1', name: 'Trần Quốc Bảo',    dept: 'Tư pháp – Hộ tịch',        area: 'Cẩm Thành, Trần Hưng Đạo', position: 'Chuyên viên', workload: 3 },
    { id: 'of2', name: 'Lê Thị Thu Trang', dept: 'Bộ phận Một cửa',          area: 'Toàn thành phố',           position: 'Chuyên viên chính', workload: 4 },
    { id: 'of3', name: 'Phạm Văn Hùng',    dept: 'Quản lý đô thị',           area: 'Quảng Phú, Nghĩa Chánh',   position: 'Phó phòng', workload: 3 },
    { id: 'of4', name: 'Võ Minh Châu',     dept: 'Tài nguyên – Môi trường',  area: 'Trương Quang Trọng',       position: 'Chuyên viên', workload: 2 },
    { id: 'of5', name: 'Đặng Hữu Phước',   dept: 'Công an TP',               area: 'Nghĩa Lộ, Chánh Lộ',       position: 'Đội trưởng', workload: 2 },
  ],
  departments: ['Bộ phận Một cửa', 'Tư pháp – Hộ tịch', 'Quản lý đô thị', 'Tài nguyên – Môi trường', 'Công an TP', 'Văn phòng UBND'],
  positions: ['Chuyên viên', 'Chuyên viên chính', 'Phó phòng', 'Trưởng phòng', 'Đội trưởng'],

  adminUnits: [
    { code: '51',    level: 'province', name: 'Tỉnh Quảng Ngãi', parent: '—' },
    { code: '51-01', level: 'district', name: 'TP. Quảng Ngãi',  parent: 'Tỉnh Quảng Ngãi' },
    { code: '51-02', level: 'district', name: 'TX. Đức Phổ',     parent: 'Tỉnh Quảng Ngãi' },
    { code: '51-01-01', level: 'ward', name: 'P. Cẩm Thành',           parent: 'TP. Quảng Ngãi' },
    { code: '51-01-02', level: 'ward', name: 'P. Trần Hưng Đạo',       parent: 'TP. Quảng Ngãi' },
    { code: '51-01-03', level: 'ward', name: 'P. Nghĩa Lộ',            parent: 'TP. Quảng Ngãi' },
    { code: '51-01-04', level: 'ward', name: 'P. Chánh Lộ',            parent: 'TP. Quảng Ngãi' },
    { code: '51-01-05', level: 'ward', name: 'P. Trương Quang Trọng',  parent: 'TP. Quảng Ngãi' },
    { code: '51-01-06', level: 'ward', name: 'P. Quảng Phú',           parent: 'TP. Quảng Ngãi' },
    { code: '51-01-07', level: 'ward', name: 'P. Nghĩa Chánh',         parent: 'TP. Quảng Ngãi' },
  ],

  sentNotifications: [
    { id: 'sn1', type: 'broadcast', at: '09/06/2026 08:00', title: 'Từ 15/6: tiếp nhận cấp đổi CCCD sáng thứ Bảy', recipients: '48.230' },
    { id: 'sn2', type: 'emergency', at: '26/05/2026 14:35', title: 'Cảnh báo tin nhắn giả mạo Cổng DVC yêu cầu OTP', recipients: '52.114' },
    { id: 'sn3', type: 'push',      at: '14/05/2026 09:35', title: 'Hồ sơ QNG-2026-03977 cần bổ sung giấy tờ', recipients: '1' },
    { id: 'sn4', type: 'broadcast', at: '02/05/2026 07:30', title: 'Lịch tiếp công dân tháng 5/2026 của lãnh đạo UBND TP', recipients: '47.886' },
  ],

  auditLogs: [
    { at: '11/06/2026 08:31', user: 'Phạm Quốc Trung', action: 'update', entity: 'service_points',  detail: 'Cập nhật giờ làm việc — Trung tâm PVHCC tỉnh', ip: '10.84.2.15' },
    { at: '11/06/2026 08:12', user: 'Nguyễn Thị Minh Hà', action: 'login', entity: 'users',         detail: 'Đăng nhập qua VNeID', ip: '113.185.40.22' },
    { at: '11/06/2026 07:31', user: 'Trần Quốc Bảo', action: 'status', entity: 'service_requests',  detail: 'QNG-2026-04812: Đã tiếp nhận → Đang xử lý', ip: '10.84.2.31' },
    { at: '10/06/2026 21:17', user: 'Lương Thành Đạt', action: 'role', entity: 'user_roles',        detail: 'Gán vai trò Quản trị viên cho trung.pham@…', ip: '10.84.1.4' },
    { at: '10/06/2026 16:55', user: 'Phạm Quốc Trung', action: 'create', entity: 'notifications',   detail: 'Broadcast: Lịch cắt điện khu vực Quảng Phú 12/6', ip: '10.84.2.15' },
    { at: '10/06/2026 14:22', user: 'Phạm Văn Hùng', action: 'status', entity: 'feedback_reports',  detail: 'PA-2026-0140: Đã phân công → Đang xử lý', ip: '10.84.2.40' },
    { at: '10/06/2026 09:05', user: 'Phạm Quốc Trung', action: 'create', entity: 'public_services', detail: 'Thêm thủ tục: Xác nhận tốt nghiệp tạm thời', ip: '10.84.2.15' },
    { at: '09/06/2026 15:48', user: 'Lê Thị Thu Trang', action: 'update', entity: 'service_requests', detail: 'QNG-2026-04907: thêm ghi chú nội bộ', ip: '10.84.2.28' },
    { at: '09/06/2026 10:30', user: 'Phạm Quốc Trung', action: 'delete', entity: 'service_categories', detail: 'Xóa lĩnh vực trùng lặp: "Hộ tịch (cũ)"', ip: '10.84.2.15' },
    { at: '08/06/2026 17:02', user: 'Lương Thành Đạt', action: 'update', entity: 'wards',           detail: 'Đổi tên P. Nghĩa Chánh (chuẩn hóa mã 51-01-07)', ip: '10.84.1.4' },
    { at: '08/06/2026 08:44', user: 'Hồ Thị Kim Oanh', action: 'login', entity: 'users',            detail: 'Đăng nhập thất bại (tài khoản vô hiệu)', ip: '171.224.18.90' },
    { at: '07/06/2026 13:20', user: 'Đặng Hữu Phước', action: 'status', entity: 'feedback_reports', detail: 'PA-2026-0151: Đã tiếp nhận → Đã phân công', ip: '10.84.3.7' },
  ],
};

window.ROLE_META = window.ADATA.roleMeta;
window.AUDIT_ACTION_META = {
  create: { labelKey: 'act_create', tone: 'success' },
  update: { labelKey: 'act_update', tone: 'info' },
  delete: { labelKey: 'act_delete', tone: 'danger' },
  login:  { labelKey: 'act_login',  tone: 'neutral' },
  role:   { labelKey: 'act_role',   tone: 'warning' },
  status: { labelKey: 'act_status', tone: 'info' },
};
